server:
  port: 5023

spring:
  application:
    name: image-service
  profiles:
    active: dev-local

  cloud:
    config:
      enabled: false
      fail-fast: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

